name: CI - .NET Docker Build & Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore DotNet.API/DotNet.API.csproj

    - name: Build .NET
      run: dotnet build --no-restore DotNet.API/DotNet.API.csproj

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./DotNet.API
        file: ./DotNet.API/Dockerfile
        push: true
        tags: amineelftouhi01/dotnet-api:latest, amineelftouhi01/dotnet-api:${{ github.run_number }}

